baseURL = 'www.chaoschampion.website'
languageCode = 'en-us'
title = 'junkyahd'
theme = 'hugo-book'
relativeURLs=true
enableGitInfo = true




# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true



[params]

    BookTheme = 'light'
    BookToC = true
    BookMenuBundle = '/menu'
    BookSection = 'docs'
    BookDateFormat = 'Jan 2, 2006'
    BookSearch = true
    BookComments = true
